import mongoose from 'mongoose';

const evidenceSchema = new mongoose.Schema(
  {
    evidenceId: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true,
    },
    fileName: {
      type: String,
      required: true,
      trim: true,
    },
    fileType: {
      type: String,
      required: true,
    },
    fileSize: {
      type: String,
      required: true,
    },
    fileUrl: {
      type: String,
      required: true,
    },
    linkedMission: {
      type: String,
      default: 'None', // missionCode
    },
    linkedReport: {
      type: String,
      default: 'None', // reportId
    },
    uploadedBy: {
      type: String, // officerId
      required: true,
    },
    hash: {
      type: String,
      default: '', // cryptographic checksum generated by thread
    },
    status: {
      type: String,
      required: true,
      enum: ['Processing', 'Processed', 'Quarantined', 'Failed'],
      default: 'Processing',
    },
  },
  {
    timestamps: true,
  }
);

evidenceSchema.index({ fileType: 1, status: 1 });
evidenceSchema.index({ fileName: 'text', uploadedBy: 1 });

const Evidence = mongoose.model('Evidence', evidenceSchema);
export default Evidence;
